### ISSUE TITLE
Error with Sankey Plot

### ISSUE THREAD

**Issue by JessicaP94** [enblacar/SCpubr#12]
Hello, I am trying to do a Sankey Plot but I receive this error and no plot is done.
```
Error: 'do_SankeyPlot' is not an exported object from 'namespace:SCpubr'
```
How can I solve it?

Thanks

**Comment by enblacar** [comment]
Hi @JessicaP94, thanks for using my package!

That error is basically due to the fact that there are some functions **outside** the official CRAN package, due to several reasons beyond my capability to fix them (they make use of a github package, they write to the file system, etc).

`SCpubr::do_SankeyPlot()` is one of them. If you want to make use of these functions, please always refer to SCpubr's [GitHub releases](https://github.com/enblacar/SCpubr/releases) and always download the latest **development stable** release (denoted by "-dev-stable" in the name). Those are exactly the same as the latest CRAN release, but with the additional functions. Follow the instructions [here](https://github.com/enblacar/SCpubr/releases/tag/v1.0.4-dev-stable) to download it!

In your specific case, please have a look at [`SCpubr::do_AlluvialPlot()`](https://enblacar.github.io/SCpubr-book/13-AlluvialPlot.html), as this will become the official CRAN replacement of `SCpubr::do_SankeyPlot()` once update 1.1.0 goes to CRAN.

Hope this helps!
Enrique

**Comment by JessicaP94** [comment]
Hello Enrique,
so for now is it normal that I get the same error if I try to do an
Alluvial Plot?

Thank you!

**Comment by enblacar** [comment]
Hi @JessicaP94,

SCpubr version [1.1.0](https://github.com/enblacar/SCpubr/releases/tag/v1.1.0) is already on CRAN!

Please consider updating to get all the new functionalities:

```r
install.packages("SCpubr")
```

Thanks again for using the package!
Enrique
