### ISSUE TITLE
do_LigandReceptorPlot Source/Target order

### ISSUE THREAD

**Issue by Projectnix** [enblacar/SCpubr#16]
Hi there,

Is there any way to set a custom order for the sources/targets in a do_LigandReceptorPlot?

For example, by default, the plot gives me X Z Y as my sources - I would like to rearrange that into X Y Z (I'm also using keep_source).

I tried setting the order via a fixed factor level in the table for each method e.g. factor(liana$natmi$source, levels = c("X", "Y", "Z")) but unfortunately I believe the order is lost when the function runs liana_aggregate() independently. Any ideas on how to force the order?

Perhaps in the future it may be possible to run do_LigandReceptorPlot() on the aggregated data, which will be done on the user's end.

**Comment by enblacar** [comment]
Hi @Projectnix,

Thanks for using my package!

Right now, there is not such a possibility of a custom order. I limited it to it being ordered by `significance`, `magnitude`, `both` or `alphabetically` (and the possibility of reverse it). As setting the levels yourself requires you to have the results available beforehand and given the data processing that happens after `liana::liana_aggregate()` in `SCpubr::do_LigandReceptorAnalysis()`  to arrive to the final plot, I decided to limit the freedom of input from the user. 

As I need to look into liana again since the developers updated it not long ago, I can also have a look at your request of setting factor levels and providing an aggregated object directly!

However, it might take some time for this to happen. Hope you understand! And also I hope the rest of the package is working great for you!

Best,
Enrique
