### ISSUE TITLE
pseudotime Analysis

### ISSUE THREAD

**Issue by hmlopezbertoni** [enblacar/SCpubr#18]
Thanks again for creating such a useful tool for scRNA-Seq analysis!

I was wondering if one can use Dyno instead of Monocle (since it's unavailable at this time) to create the pseudotime partitions for for the analysis? If not, do you have plans to update this function in the near future?

**Comment by enblacar** [comment]
Hello @hmlopezbertoni,

Thanks for using the package!

I recently saw that Monocle3 had already removed the dependency to Matrix.util, so the problem should be theoretically solved. 

Since I have to revisit the Pseudotima analysis section, might as well also have a look at Dyno! However, I can not really promise any specific timepoint for this to happen, due to current project overload. Thanks for understanding and pointing out to the tool!

Best,
Enrique

**Comment by hmlopezbertoni** [comment]
Awesome! Thanks for the update. 

Keep up the amazing work!
