### ISSUE TITLE
Feature request: add min/max cutoff do_FeaturePlot

### ISSUE THREAD

**Issue by ccruizm** [enblacar/SCpubr#2]
Hello @enblacar,

Really enjoy the many possibilities your package offers for data visualization. I just started using it, and the first thing I wanted to do was to plot a feature plot and limit the color scale to a range of values but could not find an option as in `FeaturePlot` (min.cutoff-max.cutoff). It would be nice if it could be added to the `do_FeaturePlot` function. :)

Thanks for this excellent package!

**Comment by enblacar** [comment]
Hello @ccruizm,

Thanks for using my package! I am happy that you like it!

Indeed, that is a very interesting feature. Probably, the feature was not present in `Seurat` when I first coded `SCpubr::do_FeaturePlot()` (it was one of the very first in the package).  I will put it in the To-Do list for the next update :P!

In the meantime, you can use the following hotfix to get the same results as you would get with `Seurat::FeaturePlot()`:

```r
#' Modify scales of a Feature Plot.
#' 
#' This function transforms all the values in a FeaturePlot that are below min.cutoff to min.cutoff and above max.cutoff to max.cutoff, effectively
#' achieving the same behaviour as in Seurat::FeaturePlot. All credits for this idea goes to the Seurat developers.
#' 
#' @param p Plot resulting from calling SCpubr::do_FeaturePlot() with a single feature and no extra parameters.
#' @param feature Feature used in p.
#' @param min.cutoff Minimum range of the scale.
#' @param max.cutoff Maximum range of the scale.
#'
#' @return A ggplot2 object with the scales modified.
#' @export
#'
#' @examples
modify_scales <- function(p,
                          feature,
                          min.cutoff = NULL,
                          max.cutoff = NULL){
  `%>%` <- magrittr::`%>%`
  `:=` <- rlang::`:=`
  
  # Apply min.cutoff.
  if (!is.null(min.cutoff)){
    p$data <- p$data %>% 
              dplyr::mutate("{feature}" := ifelse(.data[[feature]] < min.cutoff, min.cutoff, .data[[feature]]))
  }
  
  # Apply max.cutoff.
  if (!is.null(max.cutoff)){
    p$data <- p$data %>% 
              dplyr::mutate("{feature}" := ifelse(.data[[feature]] > max.cutoff, max.cutoff, .data[[feature]]))
  }
  
  return(p)
}
```

Let's use this case as an example:
```r
# SCpubr
p1 <- SCpubr::do_FeaturePlot(sample, 
                             features = "LYN")

# Seurat
p2 <- Seurat::FeaturePlot(sample, 
                          features = "LYN") + 
      ggplot2::scale_color_viridis_c(option = "G")

p <- p1 | p2
p
```
![scale_test_3](https://user-images.githubusercontent.com/42321264/196735389-e77b4860-fcdf-4936-b2bf-42075f3d0945.png)

Let's say, we want to modify the scale so that it plots values between `1` and `1.5`. With this function, you just need to provide the resulting plot of calling `SCpubr::do_FeaturePlot()`, with the values of `min.cutoff`, `max.cutoff` that you want. Like this:

```r
# Limit in the scale - SCpubr (hotfix)
p1 <- SCpubr::do_FeaturePlot(sample,
                             features = "LYN")
p1 <- modify_scales(p = p1,
                    feature = "LYN",
                    min.cutoff = 1,
                    max.cutoff = 1.5)
p

# Limit in the scale - Seurat
p2 <- Seurat::FeaturePlot(sample, 
                          features = "LYN",
                          min.cutoff = 1,
                          max.cutoff = 1.5) + 
      ggplot2::scale_color_viridis_c(option = "G")

p <- p1 | p2
p
```
This should give the same output! 
![scale_test](https://user-images.githubusercontent.com/42321264/196733151-e1c84f09-3dbc-40c8-965c-8426617ccbb9.png)

However, as I had a look into how `Seurat` does it, I noticed the following:
- If you just used `gggplo2::scale_color_viridis_c(limits = c(1, 1.5)` you will get your Feature plot full of grey dots, corresponding to NA values. 
- Looking into `Seurat's` code, I noticed that they then convert the cells outside the range to the minimum and maximum values. Therefore, take this into account when using this feature, that the end colors of the continuous scale represent **cells outside the desired range**, and not the actual values. This is specially important for the values below `min.cutoff`. 

An easy way to avoid this issue is to leave `min.cutoff = NULL` if you just want to eliminate those sparse cells with very high values in your plot:

```r
# Limit in the scale but keep low values - SCpubr (hotfix)
p <- SCpubr::do_FeaturePlot(sample,
                            features = "LYN")
p <- modify_scales(p = p,
                   feature = "LYN",
                   min.cutoff = NULL,
                   max.cutoff = 1.5)
p
```

![scale_test_2](https://user-images.githubusercontent.com/42321264/196734491-a6c931d1-507b-4775-b6f6-2fc13d254fec.png)

I hope this helps!
Enrique

**Comment by ccruizm** [comment]
Thank you for the clear and detailed reply! It definitely helps. Will give it a try, keeping in mind the drawback you mentioned. Again, really cool package :)

**Comment by w2felix** [comment]
Great hotfix, sadly it does not allow a larger max.cutoff than the maximum value in this category. For example: I have a very lowly expressed gene and I want to compare it to a highly expressed gene: If I don't set the scales to the same range, on the first glimpse, it would look like the lowly expressed gene is as high expressed as the strongly expressed gene (until you check the scale).

**Comment by enblacar** [comment]
Hi @ccruizm,

In [SCpubr v1.0.2](https://github.com/enblacar/SCpubr/blob/main/NEWS.md) `min.cutoff` and `max.cutoff` should work as intended and can now be used as parameters to the `SCpubr::do_DimPlot()` function.  

Please update the package from `CRAN` and I hope it works well for you!

Thanks for your feedback!
Enrique

**Comment by ccruizm** [comment]
That's awesome! thanks for implementing it so fast! will install this update asap :)
