### ISSUE TITLE
BUG | do_LigandReceptorPlot() |"arrange_interactions_by = both" implementation

### ISSUE THREAD

**Issue by RMOsborn012** [enblacar/SCpubr#31]
First, I would like to say that I am so very happy to see a standardized scRNAseq visualization package such as this, which has made my work so much easier. I noticed when using the ```do_LigandReceptorPlot()``` function, the ```arrange_interactions_by = "both"``` argument has undesired output when arranging the ligand-receptor pairs. It appears that when "both" is selected (Uses both sca.LRscore and natmi.edge_specificity columns to arrange the interactions by their specificity and magnitude altogether), the function arranges the ligand-receptor pairs by ```natmi.edge_specificity``` then ```sca.LRscore```. Meaning one column is arranged first, then the second (more weight on the first column). Consequently, the ```top_interactions``` argument will be skewed toward the ```natmi.edge_specificity```. I suggest changing the source code to ```arrange((desc(natmi.edge_specificity) + desc(sca.LRscore)) / 2)``` or something similar so that there are equal weights on the scoring methods, and the top interactions displayed on the plot will be more accurate. 

**SCpubr version:**
```r
 ‘1.1.2.9000’
```

**Comment by enblacar** [comment]
Hi @RMOsborn012,

Thanks a lot for using my package! I am happy to see that it is useful for your work!

Indeed, you have a point there. 

I have modified the source code so that interactions are sorted by any of the following modes:
- `Specificity`.
- `Magnitude`.
- `Specificity`, then `magnitude`.
- `Magnitude`, then `specificity`.
- `Specificity` and `magnitude` with equal weights (your suggestion).

I was not able to achieve the result you suggested with your suggested code, but I managed in the end by ordering the tibble based on the `specificity`, store the order in a column, perform the same for `magnitude`, and then order the final tibble in `ascending` order based on the sum of the orders for the two columns (so that interactions that ranked high in both `magnitude` and `specificity` will have a lower number than lower ranked ones in any of the two columns).

The changes will roll out with update `v2.0.0`. It might take a while until this happens though.  If you really want to use it now, you can always download the commit where I have added this using:

```r
devtools::install_github("enblacar/SCpubr", ref = "fd203b0")
# Reload R Session
detach("package:SCpubr")
library(SCpubr)
```

Be mindful that I am still working in the update, so things might still break. Plus, it is a `major` update, so many functions have changed and parameters have been renamed.

Hope this helps!
Enrique
