### ISSUE TITLE
Marking Frequency % inside Barplot stacks

### ISSUE THREAD

**Issue by athulmenon** [enblacar/SCpubr#32]
Hi @enblacar,

I am enjoying using SCpubr, thank you for this amazing package.

**Feature request:**
```
# Adding frequency percentage in barplots
```

**Example:**
```r
I was thinking if we can mark the frequency percentages for each clusters inside each stack of barplot, it will give more insights to the visualization.
```

**Implementation:**
```r
Trying with this code.
p4 <- SCpubr::[do_BarPlot](https://rdrr.io/pkg/SCpubr/man/do_BarPlot.html)(sample, 
                         group.by = "seurat_clusters",
                         split.by = "modified_orig.ident",
                         plot.title = "With split.by - position = fill",
                         position = "fill",
                         flip = FALSE)
```

**SCpubr version:**
```r
'1.1.2.9000'
```

Thank you,,
Athul

**Comment by enblacar** [comment]
Hi @athulmenon,

Thanks for using my package!

This is something I am working on for update `v2.0.0`. However, and sadly, displaying the proportions in the plot will only work if the fractions are sufficiently big for the numbers to be seen. Otherwise, they will collapse on top of each other. An alternative is to repel the text/labels, but it also generates quite noisy visualizations.

Therefore, I decided to add the option to display the total number of observations with `add.n` parameter when `position = fill` is set, so that one can get an insight on the observations per bar. 

I am also adding a `return_data` parameter that will output a tibble with the counts and proportions displayed in the plot. This can then be used as supplementary data that goes along with the bar plot, if used for a publication.

I hope this answer helps you! All these changes will roll out when the next update is ready. Until then, you can access them via GitHub downloading the last commit. However, bear in mind that the commit versions might still have bugs and be in experimental phase!

Best,
Enrique

**Comment by athulmenon** [comment]
Hi @enblacar 

The issue is solved with updating dplyr v1.1

Regards,
Athul

**Comment by enblacar** [comment]
Hi @athulmenon,

Yes, I was gonna mention that you should update `dplyr`. 

For the `return_data`, just assign it to a variable and you should retrieve an output list with the plot and the data.frame with the data you need.

Please also consider updating to this commit: 

```r
devtools::install_github("enblacar/SCpubr", ref = "0cd9dfd")
# Reload R Session
detach("package:SCpubr")
library(SCpubr)
```

Let me know if it works!
Enrique

**Comment by athulmenon** [comment]
Thanks @enblacar,

It worked! 

Regards,
Athul

**Comment by aditisk** [comment]
Hi @athulmenon @enblacar I had a follow up question to the discussion above. Is there a way to use "return_data" and "facet.by" simultaneously ? I am only seeing the values for one of the plots getting returned but by faceting variable has 2 values. Thanks a lot in advance for your response.
