### ISSUE TITLE
Where is the function do_AzimuthAnalysisPlot

### ISSUE THREAD

**Issue by ehatl** [enblacar/SCpubr#47]
Thanks for the great package is amazing.
I tried to do the report for Azimuth annotation with this function but I can find it.
How can i get it?

**Comment by enblacar** [comment]
Hi @ehatl,

Thanks for using my package! 

`SCpubr::do_AzimuthAnalysisPlot()` was removed when changing from `v1.1.2` to `v2.0.0`. See more info here: https://github.com/enblacar/SCpubr/blob/main/NEWS.md#removed-functions-1

In short, it arrived to a point in which a lot of errors were occurring in `SCpubr` because functions such as this one would use other functions in the package and every minor change/improvement to the source functions would result in a cascade of downstream bugs. 

For the sake of simplicity, I decided to remove these internal call to other functions from all functions when upgrading to `v2.0.0`. For `SCpubr::do_AzimuthAnalysisPlot()`, this meant that the function was completely redundant, as one can generate such plots with a combination of `SCpubr::do_DimPlot()`, `SCpubr::do_FeaturePlot()` and `SCpubr::do_BarPlot()`.

If you want to still access the function, have to downgrade to `v1.1.2`. Sorry for the inconveniences!

Enrique
