### ISSUE TITLE
do_GroupwiseDEPlot with output of FindConservedMarkers

### ISSUE THREAD

**Issue by olivermccallion** [enblacar/SCpubr#48]
Hi Enrique

 I’m using your SCpubr package which is awesome – thanks for sharing it.

**Feature request:**
```
Create a GroupwiseDEPlot for conserved markers across an integrated dataset
```

So far I've created a tibble with the output of FindConservedMarkers for each cluster. The main problems I'm running into are:
1) the output of FindConservedMarkers does not necessarily give unique genes per cluster, so there's some duplication. Fixable by forcing unique gene names, but for the final plot output would ideally have a per-gene  column. 
2) When I've forced unique gene names, I get the following error:

```r
Error in .subscript.2ary(x, i, , drop = TRUE) : subscript out of bounds
```

This is my code chunk so far:
```r
cluster_names <- unique(pbmc$manual_annotation)
iteratively_find_conserved <- function(so, cluster){
  out <- FindConservedMarkers(so, ident.1 = cluster, grouping.var = "patient", only.pos = TRUE, log2fc.threshold = 0.25)
  out <- out %>% mutate(cluster = cluster)
  out['gene'] <- rownames(out)
  return(out)
}
Idents(pbmc) <- "manual_annotation"
pbmc_conserved_markers <- lapply(cluster_names, iteratively_find_conserved, so = pbmc)
pbmc_conserved_markers <- list_rbind(pbmc_conserved_markers)
deplot_tibble <- pbmc_conserved_markers %>% mutate(p_val = ((patient1_p_val + patient2_p_val + patient3_p_val + patient4_p_val)/4),
                                                   avg_log2FC = ((patient1_avg_log2FC + patient2_avg_log2FC + patient3_avg_log2FC + patient4_avg_log2FC)/4),
                                                   pct.1 = ((patient1_pct.1 + patient2_pct.1 + patient3_pct.1 + patient4_pct.1)/4),
                                                   pct.2 = ((patient1_pct.2 + patient2_pct.2 + patient3_pct.2 + patient4_pct.2)/4),
                                                   p_val_adj = ((patient1_p_val_adj + patient2_p_val_adj + patient3_p_val_adj + patient4_p_val_adj)/4)
                                                   )
deplot_tibble <- deplot_tibble %>% select(p_val, avg_log2FC, pct.1, pct.2, p_val_adj, cluster, gene)
rownames(deplot_tibble) <- NULL
deplot_tibble <- as_tibble(deplot_tibble)
deplot_tibble['gene'] <- make.names(deplot_tibble$gene, unique=TRUE)
 
 
p_out <- SCpubr::do_GroupwiseDEPlot(sample = pbmc, de_genes = deplot_tibble, min.cutoff = 1)
```

**SCpubr version:**
```r
2.0.2
```

Thanks again for the package, really enjoying using it!

**Comment by enblacar** [comment]
Hi @olivermccallion,

Thanks for using my package and sorry for the late reply!

I had a look at `Seurat::FindConservedMarkers()` and sadly the output greatly behaves from what `SCpubr::do_GroupwiseDEPlot()` expects, which is the output of `Seurat::FindAllMarkers()`. Right now this falls completely outside the scope of the function, because even if you fix the gene names, the function also expects a `p.adjust` and `avg_log2FC` columns, for which the output of `Seurat::FindConservedMarkers()` outputs several, one per each condition.

I am sorry not being of help here! Feel free to open another issue if there is anything else I can help you with!

Best,
Enrique
