### ISSUE TITLE
REQUEST | do_featureplot | shared espression of One or more genes

### ISSUE THREAD

**Issue by feanaros** [enblacar/SCpubr#56]
Hi, th IIank you for this wonderful package.
 *Do_featureplot with coexprn77
``` 
# My question concerns the possibility to add a function to do_featureplot that allows to plot two genes with different colors in two separate umaps, and a third plot with the coexpression of both. (See blend = T in  Seurat)
Thank you, 
Best

**Comment by enblacar** [comment]
Hi @feanaros,

Thanks for using my package! A co-expression using `blend = TRUE` is something I have been thinking about adding to `SCpubr::do_FeaturePlot()` for a while. Given this issue, I will add it to the To-Do list for the next `SCpubr` update! 

It might take a while, though, since I find myself in the middle of my PhD thesis writing with little time to play around with the package! Hope you understand!

Best,
Enrique
