### ISSUE TITLE
Feature Request: Multiple Features for do_RidgePlot

### ISSUE THREAD

**Issue by w2felix** [enblacar/SCpubr#6]
Hi,
I would love to compare the expression of two markers in the same cell type by ridge plots. It would be cool to have two colors for the two markers and directly compare them next to each other.
Thank you very much!

**Comment by enblacar** [comment]
Hi!,

Thanks for the ideas! 

As of now, I could not come up with a way to do that in a single plot. But, wouldn't this do the trick?

```r
p1 <- SCpubr::do_RidgePlot(sample = sample,
                           feature = "LYN",
                           continuous_scale = TRUE) 

p2 <- SCpubr::do_RidgePlot(sample = sample,
                           feature = "CD14",
                           continuous_scale = TRUE,
                           viridis_color_map = "D")

p <- p1 | p2
p
```
![test](https://user-images.githubusercontent.com/42321264/197609362-ac587de9-1918-47aa-9613-1cee132f7594.png)

However, as you can see, the distance between the categorical items in the Y axis is decided internally by `ggridges` (or at least, I do not know how to set it to a fixed value so that it is reproducible no matter the feature), so plotting them side by side will not get the desired output.

Therefore, I do not think this is feasible as of now with my current knowledge level. 

Best,
Enrique

**Comment by w2felix** [comment]
woho, yes, sometimes the simplest solutions are the best! why the need to have them complex in one function, if you could just put them next to each other.... :)

**Comment by enblacar** [comment]
Glad it still works for what you want to see!

I am closing the issue now, open another one if you have any other doubts/suggestions!

Best,
Enrique
