### ISSUE TITLE
REQUEST | do_DimPlot | Create UMAP with Table

### ISSUE THREAD

**Issue by shahrozeabbas** [enblacar/SCpubr#60]
Hello,

Love this package for nice single-cell visualizations!

I have a bit of a problem. I am working with a large `anndata` object that I am unable to convert to a `Seurat` object. I would like to export the UMAP embeddings and be able to create the same visualizations from `SCpubr`. Would you be willing to outline for me what steps I need to take to accomplish this? If you could point out the bits of source code that I need to repurpose to accomplish this, that would also be a big help.

Appreciate any advice you may have, thanks!

**Comment by enblacar** [comment]
Hi @shahrozeabbas,

Thanks for using my package and apologies for the late reply! I am currently writing my PhD thesis and this is taking all my time!

If the object is that big, I think it is then becoming a problem of the Seurat data structure instead. I know that in v5 they transitioned to an approach in which they generate a representative subset of the data for interactive visualization.

If your aim is the same, I would suggest you generate a representative subset of your data and that you turn it into a Seurat object. Otherwise, maybe trying with Seurat v5 and in a cluster and saving the plots to disk for inspection might do the trick!

Hope this helped!
Enrique
