### ISSUE TITLE
REQUEST | do_DotPlot | Allow duplicated features

### ISSUE THREAD

**Issue by frac2738** [enblacar/SCpubr#61]
I was wondering how easy/feasible would be to keep duplicated genes when plot genes from a list (clustering using facets).

With an example:

     genes <- list("Naive CD4+ T" = c("CD3E", "CD4","CCR7"),
              "CD8+ T" = c("CD8A","CD3E"),
              "NK" = c("GNLY", "NKG7"))

    SCpubr::do_DotPlot(sample = sample, features = genes)

The above code will return a warning saying something on the line of 

    ! Found duplicated features:
    CD3E
    In the list named: CD8+ T with regards to the other lists. 
    Excluding them from the analysis.  

and `CD3E` will be included in the first group (`Naive CD4+ T`). 
This could mislead the user in thinking that CD3E is not a marker for CD8.

Currently a workaround is to group all the "shared" markers into a general group (e.g. `T cells`), but it would be great to not have to worry about this (especially if markers are not really known).

**Comment by enblacar** [comment]
Hi @frac2738!

Thanks a lot for using my package!

The problem is that `SCpubr::do_DotPlot()` takes into account each gene as a level in a factor. Since duplicated levels are not allowed, I remove duplicated entries. In order to do what you suggest, each item on the named list will have to become an independent ggplot object that then needs to be combined, which is currently outside what is programmed for the function.

I will put this on the to-do list for future updates and see how feasible this is without a complete refactoring of the function! 

Best,
Enrique
