### ISSUE TITLE
BUG | do_FeaturePlot | diverging.palette argument is not working

### ISSUE THREAD

**Issue by venkan** [enblacar/SCpubr#62]
I'm using `SCpubr::do_FeaturePlot` with different arguments like `split.by`, `diverging.palette` etc...

```
SCpubr::do_FeaturePlot(scdata, features = c("signature"), reduction = "umap", split.by = "condition", ncol=4,
	                        order = TRUE, legend.title = "myCAF_Custom Signature", font.size = 8, plot.axes = TRUE, 
                                 legend.length = 8, legend.width = 0.5, legend.position = "bottom", pt.size=0.3,
                                 diverging.palette = "RdBu", diverging.direction = -1)
```

<img width="1290" alt="Screenshot 2024-04-11 at 23 16 28" src="https://github.com/enblacar/SCpubr/assets/11817153/722d5168-47fe-4922-8803-b7ce0f9aca7e">

As you see in the above function I'm using `diverging.palette = "RdBu"`, but still color is not changed. I tried with different `diverging.palette` but didn't work.

I'm using ‘2.0.1’ SCPubr version !!

**Comment by enblacar** [comment]
Hi @venkan,

Thanks for using my package!

In order for you to map a diverging palette to the plots, you need to use `enforce_symmetry = TRUE`. Otherwise, I only allow the use of sequential palettes for variables that are not centered, transformation that `enforce_symmetry` will perform on the data to plot if you set it to `TRUE`.

You can then set `symmetry.type` to `absolute` to make it centered around 0 or `centered` alongisde with `symmetry.center` to tailor the center to your liking.

For this, you need to update to `v2.0.2`.

Hope this helps!
Enrique

**Comment by venkan** [comment]
Thank you. When I use 

`SCpubr::do_FeaturePlot(scdata, features = c("signature"), reduction = "umap", split.by = "DiseaseGroup", ncol=4, order = FALSE, font.size = 8, plot.axes = TRUE, legend.length = 8, legend.width = 0.5, legend.position = "bottom", pt.size=0.3, enforce_symmetry=TRUE, diverging.palette="RdBu")`

<img width="1454" alt="Screenshot 2024-04-17 at 13 56 29" src="https://github.com/enblacar/SCpubr/assets/11817153/5d2b4b87-39ed-4ddb-a3df-d9509157953f">

How can I change the color scaling here? I want the `scaling from -0.5 to -0.1`

**Comment by enblacar** [comment]
In your second input, there is not `enforce_symmetry = TRUE`. Can you try with that and let me know if it works? 

Best,
Enrique

**Comment by venkan** [comment]
Thanks for your quick reply. 

`SCpubr::do_FeaturePlot(scdata, features = c("signature"), reduction = "umap", split.by = "DiseaseGroup", ncol=4,order = FALSE, font.size = 8, plot.axes = TRUE,legend.length = 8, legend.width = 0.5, legend.position = "bottom", pt.size=0.3, diverging.palette="RdBu", symmetry.type = "centered", symmetry.center=-0.3, enforce_symmetry=TRUE)`

Output:

<img width="1285" alt="Screenshot 2024-04-17 at 14 39 51" src="https://github.com/enblacar/SCpubr/assets/11817153/16f0413e-828b-4ba1-8389-4dfb08049af0">

You see the above image. Scaling is wrong.

**Comment by enblacar** [comment]
Hmmm true:

Can you check one more thing?  Try adding to what you already have:
`min.cutoff = -0.5`
`max.cutoff = -0.1`

If it does not work, I will need to have check to fix the bug! 

Let me know if it works and thanks for the help!
Enrique

**Comment by enblacar** [comment]
Hmmm they look ok, apart from the fact that now the feature to plot is "signatrue" instead of "signature"...

It seems like a proper bug. I will add it to the to-do list for the next update. I am sorry it did not work!

Many thanks for the quick feedback and feel free to open another Issue if you face other problems!

Best,
Enrique

**Comment by venkan** [comment]
sorry. that's a  tyo (signature it is). Only when I use `split.by` having this problem.

**Comment by michaelplynch** [comment]
Just checking in to see has this been fixed? I'm facing similar issues on current CRAN and devel versions, but can open a new issue if this was already addressed. Thanks.

**Comment by enblacar** [comment]
Hi @venkan @michaelplynch,

Sorry for the big delay. I just pushed a commit with a fix for this issue. It will roll out with update v3.0.0, which I am currently pushing to be ready as fast as possible.

Best,
Enrique
