### ISSUE TITLE
REQUEST | do_RidgePlot | Extending Data Lines

### ISSUE THREAD

**Issue by KKnowles222** [enblacar/SCpubr#78]
**Feature request:**
```
# I am trying to make multiple ridge plots, all with the same scale.
# When using ggplot2’s command coord_cartesian to scale the graphs equally along the x-axis, the ridge plots data lines end before 
# reaching the limits I desire. If you could please add a way to extend the ridge plots data lines to different ranges. Or a way to set the boundaries for the graph.

```

**Example:**
```r
library(ggplot2)

p <- SCpubr::do_RidgePlot(sample = mysample,
                          feature = "nFeature_RNA")
p +  coord_cartesian(xlim = c(0,3.25))

# ![Ridge Plot Line Extension Example](https://github.com/user-attachments/assets/bf2aaa15-78b4-4f1e-8d2b-cf0ac86900bb)

```

**SCpubr version:**
```r
2.0.2
```

**Comment by enblacar** [comment]
Hi @KKnowles222,

Apologies for the long delay in coming back to this.

The main issue with what you are asking is that the lines will not stretch further than their maximum value (if in one sample nFeature_RNA goes up to 1000, but in another it goes to 2000, if you set the limit to 2000, the first sample will still stop at 1000). There is no way around it.

Having this said, you can indeed expand the axis with `ggplot2::coord_cartesian()`, and you can set up the grid lines so that you get a similar effect:

![39c988c3-b246-4c7f-9da9-6928d800e7a6](https://github.com/user-attachments/assets/9122d70e-9f51-4c60-a702-6837c39026be)


This can be achieved with: 
```r
p <- SCpubr::do_RidgePlot(sample, feature = "VWF")
p + ggplot2::theme(panel.grid.major.y = ggplot2::element_line(color = "black"))
```

Let me know if this helps!

Enrique
