### ISSUE TITLE
splitting featureplot without background cells from other condition

### ISSUE THREAD

**Issue by supersonSoge** [enblacar/SCpubr#80]
Hi @enblacar,

Hope you are doing well!

Is there an option to remove the darkgray background totally from the other condition when applying split.by in do_featureplot?

![image](https://github.com/user-attachments/assets/489752c7-b75f-4271-9821-a9af94378568)

thanks!

Best,
Tolga

**Comment by enblacar** [comment]
Hi @supersonSoge ,

Thanks for using my package!

Not being able to remove the grey background is an intentional behaviour. I do think you lose information by not knowing exactly how the true UMAP looks like.

Having this said, you can achieve it by manually removing the grey-dotted layers for each plot individually.
For your specific example, where there are only two groups:

```r
# Assign your plot object to p.
p <- your_plot_object

# Remove grey dotted layer.
p[[2]]$layers[[1]] <- NULL
p[[3]]$layers[[1]] <- NULL
```

Hope this helps your problem!
Enrique

**Comment by TdzBAS** [comment]
Hi @enblacar,

thanks!

Using your snippet, the points are still there:
![image](https://github.com/user-attachments/assets/fc066c93-73ae-422e-ab3a-8a44b13aa313)

and how could i also remove it after using do_Featureplot?
like : 
p[[1]][[1]][[1]][["layers"]][[1]] <- NULL
p[[1]][[2]][[1]][["layers"]][[1]] <- NULL

But then again the grey cells are still there from the other group..

![image](https://github.com/user-attachments/assets/96f52dcb-1ced-4981-a147-397b2eb2cca2)

Best,
Tolga

**Comment by enblacar** [comment]
Hi @TdzBAS,

Based on  your code, it seems  you are not fully reproducing my example:

- you should have your plot stored in `p`.
- Then, assuming your original plot, you need to access the second and third individual object as `p[[2]]` and `p[[3]]`. 
- Then, you access the layers parameter of each plot, and remove the first one, that contains the grey cells `$layers[[1]]`.

In your example, instead of using `p[[2]]$layers[[1]]`, you are using `p[[1]][[1]][[1]][["layers']][[1]]`, and I believe that is why it is not working.

Best,
Enrique

**Comment by TdzBAS** [comment]
Hi @enblacar,

for DimPlot and FeaturePlot I need different codes. For DimPlot I used your recommended code lines and for FeaturePlot I used the other:
![image](https://github.com/user-attachments/assets/55bec33e-fc68-4324-ba84-de416b136f37)

But both of them still results in the upper plots, where the cells are unfortunately still present. Do you have a solution? Its highly needed for my story telling!

Thanks!

Best,
Tolga

**Comment by enblacar** [comment]
Hi Tolga,

I want to re-iterate that this is not an intended behaviour in `SCpubr`. Therefore, the workaround is not simple.

For your specific case and accounting for a metadata variable with only two groups, and *while maintaining* `plot_cell_borders = TRUE`.

```r
# Fix for DimPlots. split.by - 2 categories.
p1 <- SCpubr::do_DimPlot(sample, split.by = "test")
p1.modified <- p1
p1.modified[[2]]$layers[c(1,2)] <- NULL
p1.modified[[3]]$layers[c(1,2)] <- NULL
p1 / p1.modified
```
![113b5ee9-7873-488d-b068-ddb1b8c94a02](https://github.com/user-attachments/assets/d5fa2561-3e51-46d2-8fbe-4254c96cb16d)


```r
# Fix for FeaturePlots. split.by - 2 categories.
p2 <- SCpubr::do_FeaturePlot(sample, features = "UMAP_1", split.by = "test")
p2.modified <- p2
p2.modified[[1]][[1]]$layers[c(1,2)] <- NULL
p2.modified[[1]][[2]]$layers[c(1,2)] <- NULL
p2/p2.modified
```
![cd56f88f-aba0-4f80-a034-426218c233a4](https://github.com/user-attachments/assets/9e0ccde8-3e35-4838-987a-7909b7eda759)

Hope this solves your request!
Enrique

**Comment by TdzBAS** [comment]
many many thanks!
